const STATUS = {
    WAITING_ASIGNATION: 'WAITING_ASIGNATION',
    ASIGNED: 'ASIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    WAITING_RESPONSE: 'WAITING_RESPONSE',
    RESOLVE: 'RESOLVE',
    FINAL_RESOLVE: 'FINAL_RESOLVE'
};

module.exports = STATUS;