const STATUS = {
    WAITING_ASIGNATION: 'WAITING_ASIGNATION',
    ASIGNED: 'ASIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    WAITING_RESPONSE: 'WAITING_RESPONSE',
    RESOLVE: 'RESOLVE',
    FINAL_RESOLVE: 'FINAL_RESOLVE',
    CLOSED_DUE_TO_INACTIVITY: 'CLOSED_DUE_TO_INACTIVITY'
};

const STATUS_TRANSLATE = {
    WAITING_ASIGNATION: 'ESPERANDO ASIGNACIÓN',
    ASIGNED: 'ASIGNADO',
    IN_PROGRESS: 'EN PROGRESO',
    WAITING_RESPONSE: 'ESPERANDO RESPUESTA',
    RESOLVE: 'RESUELTO',
    FINAL_RESOLVE: 'FINALIZADO',
    CLOSED_DUE_TO_INACTIVITY: 'CERRADO POR INACTIVIDAD'
}

getStatusTranslate = (status) => {
    return STATUS_TRANSLATE[status];
}

module.exports = {
    STATUS,
    STATUS_TRANSLATE,
    getStatusTranslate
};